annotations:
  category: Database
apiVersion: v2
appVersion: 4.0.3
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Apache Cassandra is an open source distributed database management system designed to handle large amounts of data across many servers, providing high availability with no single point of failure.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/cassandra
icon: https://bitnami.com/assets/stacks/cassandra/img/cassandra-stack-220x234.png
keywords:
  - cassandra
  - database
  - nosql
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: cassandra
sources:
  - https://github.com/bitnami/bitnami-docker-cassandra
  - http://cassandra.apache.org
version: 9.1.21
