FROM registry.redhat.io/ubi8/ubi

RUN REPOLIST=rhel-8-for-x86_64-rt-rpms \
    PKGLIST="kernel-tools grubby tuned rt-tests rteval" && \
    yum -y install --enablerepo ${REPOLIST} ${PKGLIST} && \
    yum -y clean all

USER 0
ENV APP_ROOT=/opt/rt-tests
ENV PATH=${APP_ROOT}:${PATH} HOME=${APP_ROOT}
COPY scripts ${APP_ROOT}
WORKDIR ${APP_ROOT}

ENTRYPOINT ["/opt/rt-tests/entrypoint.sh"]