ARG REGISTRY=registry.redhat.io
FROM $REGISTRY/ubi7/ubi

RUN REPOLIST=rhel-7-server-rt-rpms \
    PKGLIST="rt-tests rteval procps-ng" \
    && yum -y install --enablerepo ${REPOLIST} ${PKGLIST} \
    && yum -y clean all \
    && rm -rf /var/cache/yum

USER 0
ENV APP_ROOT=/opt/rt-tests HOME=${APP_ROOT} PATH=${APP_ROOT}:${PATH}
WORKDIR ${APP_ROOT}

ENV DURATION=1m
ENV CORE_LIST=1

CMD ["-c", "taskset -c ${CORE_LIST} rteval -v -d ${DURATION} --loads-cpulist=${CORE_LIST} --measurement-cpulist=${CORE_LIST}"]
ENTRYPOINT ["/bin/bash"]
