FROM oai-build-base:latest.centos8 AS builder

ARG GIT_TAG=latest

RUN git clone --depth=1 --branch=stable/v1.0  git://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
RUN cd rt-tests && make cyclictest

FROM centos:8

COPY --from=builder /root/rt-tests/cyclictest /usr/local/bin/cyclictest/

ARG CORES=1
ARG CORE_LIST=2
ARG DURATION=1m

ENV CORES="${CORES}"
ENV CORE_LIST="${CORE_LIST}"
ENV DURATION="${DURATION}"
USER root

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "taskset -c ${CORE_LIST} cyclictest -q -D ${DURATION} -p 99 -t ${CORES} -h 30 -m -a ${CORE_LIST}"]

