apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-hss.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-hss.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-hss.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Chart.Name }}-net1
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: init-db
        image: "{{ .Values.cassandra.repository }}:{{ .Values.cassandra.version }}"
        command:
        - sh
        - -c
        - cqlsh cassandra -u cassandra -p cassandra --file /root/oai_db.cql
        volumeMounts:
        - mountPath: /root
          name: db-schema
      containers:
      - name: hss
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: 3868
          name: oai-hss
        - containerPort: 5868
          name: oai-hss-secure
        - containerPort: 9080
          name: jmx
        - containerPort: 9081
          name: cql
        # volumeMounts:
        # - mountPath: /opt/oai-hss/certs
        #   name: certs
        env:
          - name: PREFIX
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: prefix
          - name: HSS_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: identity
          - name: REALM
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: realm
          - name: cassandra_Server_IP
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: dbFqdn
          - name: OP_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: opKey
          - name: ROAMING_ALLOWED
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: roaming
          - name: APN1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: apn1
          - name: APN2
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: apn2
          - name: LTE_K
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: lteK
          - name: FIRST_IMSI
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: imsi
          - name: NB_USERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: numSubscribers
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        imagePullPolicy: {{ .Values.tcpdumpimage.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.enabled}}
        volumeMounts:
        - mountPath: "/pcap"
          name: cn4g-pv
        {{- end}}
      volumes:
      {{- if .Values.persistence.enabled}}
      - name: cn4g-pv
        persistentVolumeClaim:
          claimName: cn4g-pvc
      {{- end }}
      - configMap:
          name: oai-db
        name: db-schema
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

