---
{{- if .Values.persistence.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: cn4g-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.volumeName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end}}
