---
{{- if .Values.persistence.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: cn5g-pvc
#  name: {{.Chart.Name}}-{{ .Release.Namespace }}-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.volumeName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end}}
