#!/bin/bash

info() {
    local MESSAGE=$1

    echo -e "\E[34m\n== $MESSAGE\E[00m";
}


THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
${THIS_SCRIPT_PATH}/check_system_rt_config

source /etc/os-release
PLATFORM=${PLATFORM:-${ID#rh*}${VERSION_ID%.*}}
info "Running rt-tests.${PLATFORM} image"
podman run --rm --privileged --cap-add=SYS_RAWIO --cap-add=SYS_NICE --cap-add=IPC_LOCK -it rt-tests:latest.${PLATFORM}