{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistent.volumeName }}
  resources:
    requests:
      storage: {{ .Values.persistent.size }}
{{- end }}
