{{- if (include "cassandra.createTlsSecret" . ) }}

{{- $tlsCertStr := regexSplit "###" (include "cassandra.getTlsCertStrFromSecret" .) -1 }}
{{- $ca := index $tlsCertStr 0 }}
{{- $crt := index $tlsCertStr 1 }}
{{- $key := index $tlsCertStr 2 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-crt
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca | b64enc | quote }}
  tls.crt: {{ $crt | b64enc | quote }}
  tls.key: {{ $key | b64enc | quote }}
{{- end }}
