# Default values for oai-spgwu-tiny.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: local
  repository: oai-spgwu-tiny
  version: oai-oc
  # pullPolicy: IfNotPresent or Never or Always
  pullPolicy: Always

tcpdumpimage:
  registry: local
  repository: network-tools-rhel8
  version: v4.10.0-202205022327.p0.gbcfec9c.assembly.stream
  #pullPolicy: IfNotPresent or Never or Always
  pullPolicy: IfNotPresent



persistence:
  # make it true for the first time when you want to create persistance volume
  # and then false
  enabled: true
  volumeName: nfs-client
  size: 1Gi

multus:
  hostInterface: "bond0"      # Interface of the host machine on which this pod will be scheduled

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "oai-spgwu-tiny-sa"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "NET_RAW"]
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  pfcpPort: 8805
  gtpuPort: 2152

start:
  spgwu: true
  tcpdump: false
log:
  # Leave string empty to disable
  stdout: " -o "
  file: " -r "
lte:
  instance: 0
  fqdn: "oai-spgwu-tiny-0"
  pidDirectory: "/var/run"
  spgwSxIf: "eth0"
  pgwuS1uIf: "net1"
  pgwuSgiIf: "net1"
  spgwS1uIp: "172.21.6.183"
  spgwNetmaskS1u: "22"
  pgwuSgiGw: "172.21.7.254"
  netUeIp: "192.168.29.0/24"
  pgwcSxIp: "172.21.6.181"
  netUeNatOption: "yes"
  threadsS1uUl: "16"
  threadsSgiDl: "16"
  threadsSx: "1"
  threadsSgiPrio: "64"
  threadsS1uPrio: "64"
  threadsSxPrio: "64"
  # standart feature is no, put yes if you want less UL packet delay
  bypassUlPfcpRules: "yes"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 8
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

terminationGracePeriodSeconds: 30

nodeName: 

